src/Entity/Tricks.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TricksRepository")
 */
class Tricks
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\TricksGroup", inversedBy="tricks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $TrickGroup;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\TricksImages", mappedBy="trick", orphanRemoval=true)
     */
    private $tricksImages;

    /**
     * @Gedmo\Slug(fields={"name"})
     * @ORM\Column(length=128, unique=true)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\TricksVideos", mappedBy="trick", orphanRemoval=true)
     */
    private $tricksVideos;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comments", mappedBy="trick", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->createdAt = new \DateTime();
        $this->updatedAt = new \DateTime();
        $this->tricksImages = new ArrayCollection();
        $this->tricksVideos = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getTrickGroup(): ?TricksGroup
    {
        return $this->TrickGroup;
    }

    public function setTrickGroup(?TricksGroup $TrickGroup): self
    {
        $this->TrickGroup = $TrickGroup;

        return $this;
    }

    /**
     * @return Collection|TricksImages[]
     */
    public function getTricksImages(): Collection
    {
        return $this->tricksImages;
    }

    public function addTricksImage(TricksImages $tricksImage): self
    {
        if (!$this->tricksImages->contains($tricksImage)) {
            $this->tricksImages[] = $tricksImage;
            $tricksImage->setTrick($this);
        }

        return $this;
    }

    public function removeTricksImage(TricksImages $tricksImage): self
    {
        if ($this->tricksImages->contains($tricksImage)) {
            $this->tricksImages->removeElement($tricksImage);
            // set the owning side to null (unless already changed)
            if ($tricksImage->getTrick() === $this) {
                $tricksImage->setTrick(null);
            }
        }

        return $this;
    }

    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * @return Collection|TricksVideos[]
     */
    public function getTricksVideos(): Collection
    {
        return $this->tricksVideos;
    }

    public function addTricksVideo(TricksVideos $tricksVideo): self
    {
        if (!$this->tricksVideos->contains($tricksVideo)) {
            $this->tricksVideos[] = $tricksVideo;
            $tricksVideo->setTrick($this);
        }

        return $this;
    }

    public function removeTricksVideo(TricksVideos $tricksVideo): self
    {
        if ($this->tricksVideos->contains($tricksVideo)) {
            $this->tricksVideos->removeElement($tricksVideo);
            // set the owning side to null (unless already changed)
            if ($tricksVideo->getTrick() === $this) {
                $tricksVideo->setTrick(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comments[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setTrick($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getTrick() === $this) {
                $comment->setTrick(null);
            }
        }

        return $this;
    }

}

src/Controller/TricksController.php
<?php

namespace App\Controller;

use App\Entity\Tricks;
use App\Entity\TricksImages;
use App\Entity\TricksVideos;
use App\Entity\Comments;
use App\Repository\TricksRepository;
use App\Repository\TricksImagesRepository;
use App\Repository\TricksVideosRepository;
use App\Repository\CommentsRepository;
use App\Form\TricksNewType;
use App\Form\CommentsType;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Filesystem\Exception\IOExceptionInterface;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TricksController extends AbstractController
{

    public function __construct(TricksRepository $TricksRepository, TricksImagesRepository $TricksImagesRepository, TricksVideosRepository $TricksVideosRepository, CommentsRepository $CommentsRepository, ObjectManager $entityManager)
    {
        
        $this->TricksRepository = $TricksRepository;
        $this->TricksImagesRepository = $TricksImagesRepository;
        $this->TricksVideosRepository = $TricksVideosRepository;
        $this->CommentsRepository = $CommentsRepository;
        $this->entityManager = $entityManager;

    }

    /**
    * @Route("/", name="app_homepage")
    */
	public function index()
	{

		$tricks = $this->TricksRepository->findAllTricks();

        
        return $this->render('home.html.twig', [
        	'tricks' => $tricks,
        	'current_menu' => 'homepage'   
        ]);

	}

    /**
     * @Route("/tricks/details/{id}-{slug}", name="tricks.details", requirements={"slug": "[a-z0-9\-]*"})
     * @return Response
     */
    public function detailsTrick(Request $request, $id)
    {

        $trick = $this->TricksRepository->find($id);
        $thumbnail = $this->TricksImagesRepository->findTrickThumbnail($trick->getId());
        $images = $this->TricksImagesRepository->findAllTrickImages($trick->getId());
        $videos = $this->TricksVideosRepository->findAllTrickVideos($trick->getId());

        $comment = new Comments();
        $form = $this->createForm(CommentsType::class, $comment, [
            'action' => $this->generateUrl('comments_new',array('id' => $trick->getId())),
        ]);
        $form->handleRequest($request);

        $comments = $this->CommentsRepository->findBy(['trick' => $id],['createdAt' => 'DESC']);

        return $this->render('tricks/details.html.twig', [
            'trick' => $trick,
            'thumbnail' => $thumbnail,
            'images' => $images,    
            'videos' => $videos,
            'commentForm' => $form->createView(),
            'comments' => $comments
        ]);

    }

	/**
    * @Route("/new-trick", name="tricks.new")
    */
    public function newTrick(Request $request): Response
    {
        
        $trick = new Tricks();
        $image1 = new TricksImages();

        $formTrick = $this->createForm(TricksNewType::class, $trick);
        $formTrick->handleRequest($request);

        if ($formTrick->isSubmitted()) {

            $entityManager = $this->getDoctrine()->getManager();

            $entityManager->persist($trick);
            $entityManager->flush();

            $tricks_directory = $this->getParameter('tricks_directory');

            $thumbnailFile = $formTrick['tricksImages']['thumbnail']->getData();
            $additionalFile = $formTrick['tricksImages']['additional']->getData();

            if (isset($thumbnailFile)) {

                try {

                    $filename = uniqid() .'.' .$thumbnailFile->guessExtension();
                    $thumbnailFile->move($tricks_directory, $filename);

                } catch (FileException $e) {

                }

                $image1->setTrick($trick);
                $image1->setFilename($filename);
                $image1->setIsThumbnail(1);
                $entityManager->persist($image1);
                $entityManager->flush();

            } else {

                $image1->setTrick($trick);
                $image1->setFilename('default.png');
                $image1->setIsThumbnail(1);
                $entityManager->persist($image1);
                $entityManager->flush();

            }

            if (isset($additionalFile)) {

                foreach ($additionalFile as $file) {

                    $image2 = new TricksImages();

                    try {

                        $filename = uniqid() .'.' .$file->guessExtension();
                        $file->move($tricks_directory, $filename);
                        
                    } catch (Exception $e) {
                        
                    }

                    $image2->setTrick($trick);
                    $image2->setFilename($filename);
                    $image2->setIsThumbnail(0);
                    $entityManager->persist($image2);

                }

                $entityManager->flush();

            }

            $videosUrl = $request->request->get('add-video');

            if (isset($videosUrl)) {

                foreach ($videosUrl as $videoUrl) {
                    
                    $video = new TricksVideos();

                    preg_match('/<iframe.*src=\"(.*)\".*><\/iframe>/isU', $videoUrl, $url);
                
                    $video->setTrick($trick);
                    $video->setUrl($url[1]);
                    $entityManager->persist($video);
                    $entityManager->flush();

                }

            }

            $this->addFlash('trick-success','Your trick has been added to our list.');

            return $this->redirectToRoute('app_homepage');

        }

        return $this->render('tricks/new.html.twig', [
            'trickNewForm' => $formTrick->createView(),
            'current_menu' => 'tricks'
        ]);

    }

    /**
     * @Route("/tricks/edit/{id}", name="tricks.edit", methods="GET|POST")
     * @param Tricks $trick
     */
    public function editTrick(Tricks $trick, Request $request)
    {

        $editForm = $this->createForm(TricksNewType::class, $trick);
        $editForm->handleRequest($request);

        $thumbnail = $this->TricksImagesRepository->findTrickThumbnail($trick->getId());
        $images = $this->TricksImagesRepository->findAllTrickImages($trick->getId());
        $videos = $this->TricksVideosRepository->findAllTrickVideos($trick->getId());

        if ($editForm->isSubmitted()) {

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($trick);
            $this->entityManager->flush();

            $tricks_directory = $this->getParameter('tricks_directory');

            $thumbnailFile = $editForm['tricksImages']['thumbnail']->getData();
            $additionalFile = $editForm['tricksImages']['additional']->getData();

            if (isset($thumbnailFile)) {

                $thumbnail = $this->TricksImagesRepository->findTrickThumbnail($trick->getId());
                $filename = $thumbnail->getFilename();
                $filesystem = new Filesystem();
                $filesystem->remove($tricks_directory .'/' .$filename);

                $this->entityManager->remove($thumbnail);

                $image1 = new TricksImages();

                try {

                    $filename = uniqid() .'.' .$thumbnailFile->guessExtension();
                    $thumbnailFile->move($tricks_directory, $filename);

                } catch (FileException $e) {

                }

                $image1->setTrick($trick);
                $image1->setFilename($filename);
                $image1->setIsThumbnail(1);
                $entityManager->persist($image1);
                $entityManager->flush();

            }

            if (isset($additionalFile)) {

                foreach ($additionalFile as $file) {

                    $image2 = new TricksImages();

                    try {

                        $filename = uniqid() .'.' .$file->guessExtension();
                        $file->move($tricks_directory, $filename);
                        
                    } catch (Exception $e) {
                        
                    }

                    $image2->setTrick($trick);
                    $image2->setFilename($filename);
                    $image2->setIsThumbnail(0);
                    $entityManager->persist($image2);

                }

                $entityManager->flush();

            }

            $videosUrl = $request->request->get('add-video');

            if (isset($videosUrl) && !empty($videosUrl[0])) {

                foreach ($videosUrl as $videoUrl) {
                    
                    $video = new TricksVideos();

                    preg_match('/<iframe.*src=\"(.*)\".*><\/iframe>/isU', $videoUrl, $url);
                
                    $video->setTrick($trick);
                    $video->setUrl($url[1]);
                    $entityManager->persist($video);
                    $entityManager->flush();

                }

            }

            $this->addFlash('trick-success', 'L\'annonce a bien été modifiée');
            return $this->redirectToRoute('app_homepage');

        }

        return $this->render('tricks/edit.html.twig', [
            'trick' => $trick,
            'thumbnail' => $thumbnail,
            'images' => $images,    
            'videos' => $videos,
            'editForm' => $editForm->createView()
        ]);

    }

    /**
     * @Route("/tricks/details/{id}", name="tricks.delete", methods="DELETE")
     * @param Tricks $trick
     */

templates/tricks/details.html.twig
{% block title %}Snowtricks - {{ trick.name }}{% endblock %}
{% extends "base.html.twig" %}
{% block body %}

	<div class="container">
		<div class="content trick-details py-5">
			<div class="trick-header" style="background-image: url({{ asset('img/tricks/') ~ thumbnail.filename }})">
				<div class="blur"></div>
				<h1>{{ trick.name }}</h1>
				{% if app.user %}
					<div class="actions">
						<a href="{{ path('tricks.edit', {id: trick.id}) }}"><i class="fad fa-pencil-alt fa-lg"></i></a>
						<form method="POST" action="{{ path('tricks.delete', {id: trick.id}) }}" class="d-inline-block" onsubmit="return confirm('Are you sure you want to delete this trick ?')">
							<input type="hidden" name="_method" value="DELETE">
							<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ trick.id) }}">
							<button class="btn p-0 text-danger"><i class="fad fa-trash-alt fa-lg"></i></button>
						</form>
					</div>
				{% endif %}
			</div>
			<button class="col-8 btn btn-primary d-block d-sm-none mx-auto my-3 btn-show-medias">See medias</button>
			<div class="medias d-none d-md-block">
				<div class="images">
					{% for image in images %}
						<img src="{{ asset('img/tricks/') ~ image.filename }}" alt="{{ trick.name }}">
					{% endfor %}
				</div>
				<div class="videos">
					{% for video in videos %}
						<iframe src="{{ video.url }}" frameborder="0"></iframe>
					{% endfor %}

				</div>
			</div>
			<p class="description">{{ trick.content|nl2br }}</p>
			<div class="infos col-11 mx-auto col-md-6 d-flex justify-content-between">
				<span><b class="badge">Group: </b>{{ trick.trickGroup.name }}</span>
				<span><b class="badge">Created: </b>{{ trick.createdAt|date("m/d/Y") }}</span>
				<span><b class="badge">Last update: </b>{{ trick.updatedAt|date("m/d/Y") }}</span>
			</div>
		</div>
		<hr>
		<div class="comments" id="comments">
			<h1>Comments</h1>
			<h4>Leave a comment</h4>
			{% if app.user %}
				<div class="form-comment">
					{{ form_start(commentForm) }}
						{{ form_row(commentForm.content) }}
						<input type="hidden" name="trick_id" value="{{ trick.id }}-{{ trick.slug }}">
						<input type="submit" class="btn btn-primary" value="send">
					{{ form_end(commentForm) }}
				</div>
			{% else %}
				<p>You need to <a href="{{ path('app_login') }}">Sign in</a>  to post comment, or <a href="{{ path('app_register') }}">Sign up</a></p>
			{% endif %}
			{% for message in app.flashes('comment-success') %}
				<div class="notice notice-success alert fade show" role="alert">
		            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
		            	<span aria-hidden="true">×</span>
		            </button>
		            <strong>Thanks!</strong>
		           	<br>
		           	{{ message }}
		        </div>
			{% endfor %}
			{% for message in app.flashes('comment-delete') %}
				<div class="notice notice-danger alert fade show" role="alert">
		            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
		            	<span aria-hidden="true">×</span>
		            </button>
		            <strong>It's your choice ...</strong>
		           	<br>
		           	{{ message }}
		        </div>
			{% endfor %}
			{% for comment in comments %}
				<div class="comment">
					<div class="dropdown-divider"></div>
  					<h5>{{ comment.user.username }}</h5>
					<p class="card-text pl-3">{{ comment.content }}</p>
					<div class="text-right">
						<p class="text-muted">{{ comment.createdAt|date("F jS \\a\\t g:ia") }}</p>
						{% if app.user == comment.user %}
							<form method="POST" action="{{ path('comments_delete', { id: comment.id }) }}" onsubmit="return confirm('Are you sure you want to delete your comment ?')">
								<input type="hidden" name="_method" value="DELETE">
								<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ comment.id) }}">
								<input type="hidden" name="trick_id" value="{{ trick.id }}-{{ trick.slug }}">
								<button class="btn text-danger p-1">delete</button>
							</form>
						{% endif %}
					</div>
				</div>
			{% endfor %}
			<button class="btn btn-light col-10 col-md-3" id="btn-loadmore" data-type="+">Show more comments</button>
		</div>
	</div>

{% endblock %}
{% block javascripts2 %}
	<script>
		var showMore = new ShowMoreShowLess;
		showMore.run('.comment', '#btn-loadmore', 'Show more comments', 'Show less comments');
	</script>
{% endblock %}

templates/tricks/edit.html.twig
{% block title %}SnowTricks - New Trick{% endblock %}
{% extends "base.html.twig" %}
{% block body %}

	<div class="container">
		<div class="content py-5">

			{{ form_start(editForm) }}
				<div class="col-12">
					{{ form_row(editForm.name) }}
				</div>
				<div class="col-12">
					{{ form_row(editForm.content) }}
				</div>
				<div class="col-12 col-md-4 col-lg-3">
					{{ form_row(editForm.trickGroup) }}
				</div>
				<div class="col-12">
					<span>Image(s)</span>
					<div class="pre-medias d-flex flex-wrap col-12">
						{% for image in images %}
							<div class="card" data-card-id="img-{{ image.id }}">
  								<img src="{{ asset('img/tricks/') ~ image.filename }}" alt="{{ trick.name }}" class="card-img-top">
 								<div class="card-body">
 									<button type='button' class='btn btn-del-image bg-danger text-light col-12' data-token="{{ csrf_token('delete' ~ image.id) }}" data-id="{{ image.id }}" data-path="{{ path('trick.image.delete', {id: image.id}) }}"><i class='fad fa-trash fa-lg'></i> Delete</button>
  								</div>
							</div>
						{% endfor %}
					</div>
					<div class="col-12 col-md-4">
						{{ form_row(editForm.tricksImages.thumbnail) }}
						<div class="preview-thumbnail"></div>
					</div>
					<div class="col-12 col-md-8">
						{{ form_row(editForm.tricksImages.additional) }}
						<div class="preview-additional"></div>
					</div>
				</div>
				<div class="col-12">
					<span>Video(s)</span>
					<div class="pre-medias d-flex flex-wrap col-12">
						{% for video in videos %}
							<div class="card" data-card-id="vid-{{ video.id }}">
								<iframe src="{{ video.url }}" frameborder="0" class="card-img-top"></iframe>
	 							<div class="card-body">
	 								<button type='button' class='btn btn-del-video bg-danger text-light col-12' data-token="{{ csrf_token('delete' ~ video.id) }}" data-id="{{ video.id }}" data-path="{{ path('trick.video.delete', {id: video.id}) }}"><i class='fad fa-trash fa-lg'></i> Delete</button>
	  							</div>
							</div>
						{% endfor %}
					</div>
					<p class="text-muted">Please use the platform embed button if exist (See the exemple below)</p>
					<table class="col-12">
						<tbody class="videos-field">
							<tr>
								<td style="width: 40px"><button type="button" class="btn btn-add-video text-info"><i class="fas fa-plus fa-lg"></i></button></td>
								<td><input type="text" name="add-video[]" class="form-control form-control" placeholder="<iframe>...</iframe>" /></td>
							</tr>
						</tbody>
					</table>
				</div>
				<div class="col-12 col-md-4 col-lg-2 my-3">
					<input type="submit" class="btn btn-light w-100" value="Save">
				</div>
			{{ form_end(editForm) }}
		</div>
	</div>

{% endblock %}

templates/tricks/new.html.twig
{% block title %}SnowTricks - New Trick{% endblock %}
{% extends "base.html.twig" %}
{% block body %}

	<div class="container">
		<div class="content py-5">
			{{ form_start(trickNewForm) }}
				<div class="col-12">
					{{ form_row(trickNewForm.name) }}
				</div>
				<div class="col-12">
					{{ form_row(trickNewForm.content) }}
				</div>
				<div class="col-12 col-md-4 col-lg-3">
					{{ form_row(trickNewForm.trickGroup) }}
				</div>
				<div class="row col-12">
					<div class="col-12 col-md-4">
						{{ form_row(trickNewForm.tricksImages.thumbnail) }}
						<div class="preview-thumbnail"></div>
					</div>
					<div class="col-12 col-md-8">
						{{ form_row(trickNewForm.tricksImages.additional) }}
						<div class="preview-additional"></div>
					</div>
				</div>
				<div class="col-12">
					<span>Video(s)</span>
					<p class="text-muted">Please use the platform embed button if exist (See the exemple below)</p>
					<table class="col-12">
						<tbody class="videos-field">
							<tr>
								<td style="width: 40px"><button type="button" class="btn btn-add-video text-info"><i class="fas fa-plus fa-lg"></i></button></td>
								<td><input type="text" name="add-video[]" class="form-control form-control" placeholder="<iframe>...</iframe>" /></td>
							</tr>
						</tbody>
					</table>
				</div>
				<div class="col-12 col-md-4 col-lg-2 my-3">
					<input type="submit" class="btn btn-light w-100" value="Add">
				</div>
			{{ form_end(trickNewForm) }}
		</div>
	</div>

{% endblock %}